# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "aac3c7dbcd19b36e3a64a977cceaf72c"
name = "Zest AI Logo Creator"
application_url = "https://imagecleaner.zestgpt.com/ai_logo_creator"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/ai_logo_creator/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app_subscriptions/update"]
uri = "/ai_logo_creator/webhooks/app/subscriptions_update"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "/ai_logo_creator/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://imagecleaner.zestgpt.com/ai_logo_creator/auth/callback"
]
