# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1a98f9d8ea78c914a55f18e352c6c386"
name = "Product Image Cleaner AI"
application_url = "https://imagecleaner.zestgpt.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app_subscriptions/update"]
uri = "/webhooks/app/subscriptions_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://imagecleaner.zestgpt.com/auth/callback"
]
